name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [26]
        target: [google_apis]
    steps:
    - name: checkout
      uses: actions/checkout@v2
      uses: subosito/flutter-action@v1
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86
        profile: Nexus 6
        script: bash ${{ github.workspace }}/run.sh